### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'type')

### ISSUE THREAD

**Issue by snowy1256** [techartorg/MXSPyCOM#16]
When executing the tool in Visual Studio 2017 I get the following output in the console window:
`Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'type')
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at MXSPyCOM.Program.execute_max_commands(String[] args, String filepath)
   at MXSPyCOM.Program.Main(String[] args)`
I'm using release 1.12

**Comment by JeffHanna** [comment]
Cannot reproduce, close.
